### PR TITLE
Create 'version.py' #15

### PR DESCRIPTION
**Pull request by arthurazs**
Create `version.py` and add `__version__` to `patch.py`

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/arthurazs/dota2patches/pull/18" target="_blank">ReviewNinja

**Comment by arthurazs** [comment]
See `__version__, __version_info__ = pyver.get_version`

**Comment by arthurazs** [comment]
Check [this](https://github.com/groveco/django-sql-explorer/blob/master/explorer/__init__.py)

**Comment by arthurazs** [comment]
`__version_info__` won't be implemented for now. Version name will be discussed in the future.

**Pull request merged**
